name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libsdl2-dev libsdl2-ttf-dev mingw-w64

      - name: Build for Linux
        run: |
          cd source/
          gcc -o ttt ttt.c -lSDL2 -lSDL2_ttf -lm

      - name: Build for Windows
        run: |
          cd source/
          gcc -std=c17 ttt.c -I./SDL2/include -L./SDL2/lib -Wall -lmingw32 -lSDL2main -lSDL2 -o ttt.exe

      - name: Build for Mac
        run: |
          cd source/
          gcc -o ttt-mac ttt.c -I /usr/local/include -L /usr/local/lib -lSDL2 -lSDL2_ttf

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ttt-linux
          path: ./source/ttt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ttt-windows
          path: ./source/ttt.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ttt-mac
          path: ./source/ttt-mac
