name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libsdl2-dev libsdl2-ttf-dev mingw-w64

      - name: Build for Windows
        run: |
          cd source/
          x86_64-w64-mingw32-gcc -o ttt.exe ttt.c -I../SDL2/include -L../SDL2/lib -Wall -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -lm

      - name: Build for Mac
        run: |
          cd source/
          gcc -o ttt-mac ttt.c -I /usr/local/include -L /usr/local/lib -lSDL2 -lSDL2_ttf -lm

      - name: Build for Linux
        run: |
          cd source/
          gcc -o ttt ttt.c -lSDL2 -lSDL2_ttf -lm

      - name: Get Commit Hash
        run: |
          bash scripts/hash.sh

      - name: Upload Artifacts - Windows
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "windows-${{ env.COMMIT_HASH }}"
          path: |
            ./source/ttt.exe
            ./source/SDL2.dll
            ./source/SDL2_ttf.dll
            ./source/fonts

      - name: Upload Artifacts - Mac
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "mac-${{ env.COMMIT_HASH }}"
          path: |
            ./source/ttt-mac
            ./source/fonts

      - name: Upload Artifacts - Linux
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "linux-${{ env.COMMIT_HASH }}"
          path: |
            ./source/ttt
            ./source/fonts
